name = "coffee"
license = "MIT"
licenselink = "https://github.com/dark-coffee/hugo-theme-coffee/blob/master/LICENSE"
description = ""
homepage = "http://github.com/dark-coffee/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Andy Baizon"
  homepage = "https://github.com/dark-coffee"
